# Generated by Django 4.2.25 on 2025-11-03 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='학급 이름 (예: 1학년 A반)', max_length=100, verbose_name='학급명')),
                ('academic_year', models.IntegerField(help_text='학년도 (예: 2025)', verbose_name='학년도')),
                ('semester', models.CharField(choices=[('spring', '1학기'), ('fall', '2학기')], help_text='학기 구분', max_length=10, verbose_name='학기')),
                ('description', models.TextField(blank=True, help_text='학급 설명 또는 특이사항', verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '학급',
                'verbose_name_plural': '학급',
                'ordering': ['-academic_year', 'semester', 'school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FailedSpaceCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField(help_text='공간 생성 실패 시 오류 메시지', verbose_name='오류 메시지')),
                ('retry_count', models.IntegerField(default=0, verbose_name='재시도 횟수')),
                ('last_attempted_at', models.DateTimeField(auto_now=True, verbose_name='마지막 시도 시각')),
                ('resolved', models.BooleanField(default=False, verbose_name='해결 여부')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해결 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '스페이스 생성 실패',
                'verbose_name_plural': '스페이스 생성 실패',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='학생 고유 번호', max_length=50, unique=True, verbose_name='학번')),
                ('name', models.CharField(help_text='학생 이름', max_length=100, verbose_name='이름')),
                ('grade', models.IntegerField(blank=True, help_text='학년 (1-6)', null=True, verbose_name='학년')),
                ('generated_email', models.EmailField(help_text='자동 생성된 이메일 주소 (형식: {student_id}@seoul.zep.internal)', max_length=254, verbose_name='생성된 이메일')),
                ('zep_space_url', models.URLField(blank=True, help_text='학생 개인 ZEP 스페이스 URL', max_length=500, verbose_name='ZEP 스페이스 URL')),
                ('notes', models.TextField(blank=True, help_text='학생 관련 메모', verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생',
                'ordering': ['class_assignment', 'student_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': '학교', 'verbose_name_plural': '학교'},
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, help_text='학교 주소', verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='학교 대표 이메일', max_length=254, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='학교 대표 연락처', max_length=20, verbose_name='연락처'),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text='학교 로고 이미지', null=True, upload_to='schools/logos/', verbose_name='학교 로고'),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(help_text='학교 이름', max_length=200, verbose_name='학교명'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='students_sc_name_c2a294_idx'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_assignment',
            field=models.ForeignKey(blank=True, help_text='현재 소속 학급', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.class', verbose_name='소속 학급'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자 계정'),
        ),
        migrations.AddField(
            model_name='failedspacecreation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_space_attempts', to='students.student', verbose_name='학생'),
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='학급 담당 강사', limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_classes', to=settings.AUTH_USER_MODEL, verbose_name='담당 강사'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(help_text='소속 학교', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='students.school', verbose_name='학교'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='students_st_student_e7126a_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_assignment'], name='students_st_class_a_993bad_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'academic_year', 'semester'], name='students_cl_school__fa8304_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['instructor'], name='students_cl_instruc_f7bb68_idx'),
        ),
    ]
