# Generated by Django 4.2.25 on 2025-11-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_class_failedspacecreation_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_public',
            field=models.BooleanField(default=False, help_text='스페이스를 공개 랜딩 페이지에 표시할지 여부', verbose_name='공개 여부'),
        ),
    ]
