# Generated by Django 4.2.25 on 2025-11-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['class_assignment', 'class_number', 'name'], 'verbose_name': '학생', 'verbose_name_plural': '학생'},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_student_e7126a_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='class_number',
            field=models.IntegerField(blank=True, help_text='학급 내 반 번호 (1반, 2반 등)', null=True, verbose_name='반 번호'),
        ),
        migrations.AlterField(
            model_name='student',
            name='generated_email',
            field=models.EmailField(help_text='자동 생성된 이메일 주소', max_length=254, unique=True, verbose_name='생성된 이메일'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['generated_email'], name='students_st_generat_2e59ab_idx'),
        ),
    ]
