# Generated by Django 4.2.25 on 2025-11-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_id_add_class_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='notes',
            field=models.TextField(blank=True, verbose_name='비고', help_text='학교 관련 메모'),
        ),
    ]
