# Generated by Django 4.2.25 on 2025-11-05 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0005_add_notes_to_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='이 학교를 생성한 강사', limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_schools', to=settings.AUTH_USER_MODEL, verbose_name='생성 강사'),
        ),
    ]
