# Generated by Django 4.2.25 on 2025-12-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_school_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(help_text='학교 이름 (최대 10글자)', max_length=10, verbose_name='학교명'),
        ),
    ]
