# Generated by Django 4.2.25 on 2025-12-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_change_school_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='학생 이름 (최대 10글자)', max_length=10, verbose_name='이름'),
        ),
    ]
