# Generated by Django 4.2.25 on 2025-12-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_school_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ZEP 공간의 이름 (예: 포트폴리오, 프로젝트 A 등)', max_length=200, verbose_name='공간 이름')),
                ('url', models.URLField(help_text='ZEP 스페이스 URL', max_length=500, verbose_name='ZEP 스페이스 URL')),
                ('space_id', models.CharField(blank=True, help_text='ZEP API에서 반환된 스페이스 ID', max_length=100, verbose_name='ZEP 스페이스 ID')),
                ('is_primary', models.BooleanField(default=False, help_text='학생의 대표 공간 여부', verbose_name='대표 공간')),
                ('is_public', models.BooleanField(default=False, help_text='랜딩 페이지에 공개할지 여부', verbose_name='공개 여부')),
                ('description', models.TextField(blank=True, help_text='공간에 대한 설명', verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': 'ZEP 스페이스',
                'verbose_name_plural': 'ZEP 스페이스',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['student'], name='spaces_stud_student_30afbf_idx'), models.Index(fields=['is_primary'], name='spaces_stud_is_prim_50ff9f_idx')],
            },
        ),
    ]
