# Generated by Django 4.2.25 on 2025-11-04 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_student_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_completed', models.BooleanField(default=False, help_text='강사 연수 이수 상태', verbose_name='연수 완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('affiliated_school', models.ForeignKey(blank=True, help_text='강사 소속 학교', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='students.school', verbose_name='소속 학교')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자 계정')),
            ],
            options={
                'verbose_name': '강사',
                'verbose_name_plural': '강사',
                'ordering': ['user__username'],
            },
        ),
    ]
